//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Gui.Classes {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class settings {
        
        private string dllField;
        
        private settingsFunction functionField;
        
        /// <remarks/>
        public string dll {
            get {
                return this.dllField;
            }
            set {
                this.dllField = value;
            }
        }
        
        /// <remarks/>
        public settingsFunction function {
            get {
                return this.functionField;
            }
            set {
                this.functionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class settingsFunction {
        
        private settingsFunctionManual manualField;
        
        private settingsFunctionAlgorithm algorithmField;
        
        private string nameField;
        
        /// <remarks/>
        public settingsFunctionManual manual {
            get {
                return this.manualField;
            }
            set {
                this.manualField = value;
            }
        }
        
        /// <remarks/>
        public settingsFunctionAlgorithm algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class settingsFunctionManual {
        
        private int[] enumsField;
        
        private float[] floatsField;
        
        private bool[] binariesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("enum", IsNullable=false)]
        public int[] enums {
            get {
                return this.enumsField;
            }
            set {
                this.enumsField = value;
            }
        }
        
        /// <remarks/>
        public float[] floats {
            get {
                return this.floatsField;
            }
            set {
                this.floatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("binary", IsNullable=false)]
        public bool[] binaries {
            get {
                return this.binariesField;
            }
            set {
                this.binariesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class settingsFunctionAlgorithm {
        
        private byte selectionField;
        
        private uint populationField;
        
        private float mutationField;
        
        private uint crossoverField;
        
        private settingsFunctionAlgorithmGenerations generationsField;
        
        private settingsFunctionAlgorithmRuntime runtimeField;
        
        private settingsFunctionAlgorithmFitness fitnessField;
        
        /// <remarks/>
        public byte selection {
            get {
                return this.selectionField;
            }
            set {
                this.selectionField = value;
            }
        }
        
        /// <remarks/>
        public uint population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
            }
        }
        
        /// <remarks/>
        public float mutation {
            get {
                return this.mutationField;
            }
            set {
                this.mutationField = value;
            }
        }
        
        /// <remarks/>
        public uint crossover {
            get {
                return this.crossoverField;
            }
            set {
                this.crossoverField = value;
            }
        }
        
        /// <remarks/>
        public settingsFunctionAlgorithmGenerations generations {
            get {
                return this.generationsField;
            }
            set {
                this.generationsField = value;
            }
        }
        
        /// <remarks/>
        public settingsFunctionAlgorithmRuntime runtime {
            get {
                return this.runtimeField;
            }
            set {
                this.runtimeField = value;
            }
        }
        
        /// <remarks/>
        public settingsFunctionAlgorithmFitness fitness {
            get {
                return this.fitnessField;
            }
            set {
                this.fitnessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class settingsFunctionAlgorithmGenerations {
        
        private bool selectedField;
        
        private uint valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public uint Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class settingsFunctionAlgorithmRuntime {
        
        private bool selectedField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class settingsFunctionAlgorithmFitness {
        
        private bool selectedField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool selected {
            get {
                return this.selectedField;
            }
            set {
                this.selectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
